# Htop integration 
# bind i new-window -c "#{pane_current_path}" 'htop'

# claude
bind i split-window -v -c "#{pane_current_path}" 'claude --permission-mode acceptEdits' # Open claude in new pane below
bind u split-window -v -c "#{pane_current_path}" 'htop' # Open htop in new pane below

# Nvim integration 
bind v send-keys "nvim" C-m

# Ranger integration
bind F new-window -c "#{pane_current_path}" 'ranger' # Open ranger in new window
bind f split-window -v -c "#{pane_current_path}" 'ranger' # Open ranger in new pane below

